const numbers = [12,22,23,33,44,41,45,65,57,78];
const friends = ['Abul','Kabul'];
const passed = [true, false, true];
const mixed = [12,'Feni', true,45.5];
console.log(mixed.length);
const nums = [12,43,55,67,87];
console.log(nums[2]);
nums.push(58);
console.log(nums);
nums.pop();
console.log(nums);
nums.shift();
console.log(nums);
nums.unshift('Kere Mama');
console.log(nums);